# Generated by Django 2.1.3 on 2018-11-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0003_auto_20181118_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(max_length=50),
        ),
    ]
